import { AppPlugin } from "../app/config-files.ts";
import { Logger } from "unyt_core/utils/logger.ts";
import { GitRepo } from "../utils/git.ts";
import { json2yaml } from "https://deno.land/x/json2yaml@v1.0.1/mod.ts";
import { Datex } from "unyt_core/mod.ts";
const logger = new Logger("Git Deploy Plugin");

export default class GitDeployPlugin implements AppPlugin {
	name = "git_deploy"

	async apply(data: Record<string, unknown>) {
		data = Object.fromEntries(Datex.DatexObject.entries(data));

		const gitRepo = await GitRepo.get();
		if (!gitRepo) {
			logger.warn("Git repo not found.");
			return;
		}
		const workflowDir = await gitRepo.initWorkflowDirectory();

		// TODO: also support gitlab
		const workflows = this.generateGithubWorkflows(data);

		// first delete all old uix-deploy.yml files
		for await (const entry of Deno.readDir(workflowDir.normal_pathname)) {
			if (entry.isFile && entry.name.startsWith("uix-deploy-") && entry.name.endsWith(".yml")) {
				await Deno.remove(workflowDir.getChildPath(entry.name).normal_pathname)
			}
		}

		for (const [fileName, content] of Object.entries(workflows)) {
			await Deno.writeTextFile(workflowDir.getChildPath(fileName).normal_pathname, content)
		}

	}

	generateGithubWorkflows(data: Record<string, unknown>) {
		const workflows: Record<string,string> = {}

		for (let [stage, config] of Object.entries(data)) {
			config = Object.fromEntries(Datex.DatexObject.entries(config));

			let on = config.on;
			const args = config.args;
			const branch = config.branch;
			const tests = config.tests ?? true;

			if (branch && branch !== "*") {
				on = {
					[on]: {
						branches: branch instanceof Array ? branch : [branch]
					}
				}
			}

			const env:Record<string,string> = {};
			const env_strings:string[] = []

			if (!config.secrets) config.secrets = []

			// expose GITHUB_TOKEN;
			env["GITHUB_TOKEN"] = `$\{{secrets.GITHUB_TOKEN}}`

			for (const secret of config.secrets) {
				env[secret] = `$\{{secrets.${secret}}}`
				env_strings.push(`--env ${secret}=$${secret}`)
			}

			const testJob = {
				'runs-on': 'ubuntu-latest',
				steps: [
					{
						name: 'Checkout Repo',
						uses: 'actions/checkout@v3'
					},
					{
						name: 'Setup Deno',
						uses: 'denoland/setup-deno@v1',
						// with: {
						// 	'deno-version': '1.32.5'
						// }
					},
					{
						name: 'Run Tests',
						run: 'deno run -Aq --import-map https://dev.cdn.unyt.org/importmap.json https://dev.cdn.unyt.org/unyt_tests/run.ts -s --reportfile testreport.xml'
					},
					{
						name: 'Publish Test Report',
						uses: 'mikepenz/action-junit-report@v3',
						if: 'success() || failure()',
						with: {
							report_paths: 'testreport.xml'
						}
					}
			
				]
			}

			const deployJob = {
				'runs-on': 'ubuntu-latest',
				steps: [
					{
						name: 'Checkout Repo',
						uses: 'actions/checkout@v3'
					},
					{
						name: 'Setup Deno',
						uses: 'denoland/setup-deno@v1',
						// with: {
						// 	'deno-version': '1.32.5'
						// }
					},
					{
						name: 'Deploy UIX App',
						run: `deno run --importmap https://dev.cdn.unyt.org/importmap.json -Aqr https://dev.cdn.unyt.org/uix/run.ts --stage ${stage} --detach` + (args ? ' ' + args.join(" ") : '') + (env_strings ? ' ' + env_strings.join(" ") : '')
					}
				]
			}


			const workflow = {
				name: `Deploy ${stage}`,
				on,
				env,
				jobs: {
					deploy: deployJob,
				}
			}

			if (tests) {
				deployJob.needs = 'test';
				workflow.jobs = {
					test: testJob,
					deploy: deployJob
				}
			}

			workflows[`uix-deploy-${stage}.yml`] = `# This file was auto generated by the uix git_deploy plugin. Do not manually edit.\n\n${json2yaml(JSON.stringify(workflow))}` 
		}

		return workflows
	}
}