name: update_imports

on:
  workflow_dispatch:

jobs:
  build:
    name: update imports
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Configure git
        run: |
          git config --global core.symlinks true
          git config --global fetch.parallel 32

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DENOBOT_PAT }}
          submodules: recursive

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Create PR
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
          GITHUB_TOKEN: ${{ secrets.DENOBOT_PAT }}
          GH_WORKFLOW_ACTOR: ${{ github.actor }}
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          ./tools/imports/create-pr.ts "$GITHUB_REPOSITORY"